version: '2'
services:
    assignment-app:
        image: assignment
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://assignment-postgresql:5432/assignment
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    assignment-postgresql:
        extends:
            file: postgresql.yml
            service: assignment-postgresql
